name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Steps for linting, testing, and possibly building the application...

  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t alimcs98/php-app:latest .

    - name: List Docker Images
      run: docker images

  push_docker_image:
    name: Push Docker Image
    runs-on: ubuntu-latest

    needs: [build_docker_image]  # Ensure the build job completes successfully before starting this job

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: alimcs98
        password: Mcs@12345

    - name: Print Docker Image Details
      run: |
        docker images
        docker inspect alimcs98/php-app:latest

    - name: Push Docker image to Docker Hub
      run: docker push alimcs98/php-app:latest
