name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.16'
    - name: Install Composer dependencies
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"
    - name: Install PHPUnit
      run: composer require --dev phpunit/phpunit
    - name: Verify PHPUnit installation
      run: vendor/bin/phpunit --version
    - name: Lint PHP files
      run: php -l .

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit ExampleTest.php
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . --file dockerfile -t usamashafique/php-app:latest

    - name: Build sql
      run: docker build . --file Dockerfile.mysql -t usamashafique/php-app:db
    - name: Build phpadmin
      run: docker build . --file Dockerfile.phpmyadmin -t usamashafique/php-app:phpadmin

    - name: List Docker Images
      run: docker images
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER_NAME}}
        password: ${{ secrets.USER_PASSWORD }}

    - name: Print Docker Image Details
      run: |
        docker images
        docker inspect usamashafique/php-app:latest
        while ! docker inspect usamashafique/php-app:latest &>/dev/null; do sleep 1; done

    - name: Push Docker image to Docker Hub
      run: docker push usamashafique/php-app:latest
    - name: Push Docker mysql  image to Docker Hub
      run: docker push usamashafique/php-app:db
    - name: Push Docker phpadmin  image to Docker Hub
      run: docker push usamashafique/php-app:phpadmin
