name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Steps for linting, testing, and possibly building the application...

  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . --file dockerfile -t usamashafique/php-app:latest

    - name: Build sql
      run: docker build . --file Dockerfile.mysql -t usamashafique/php-app:db
    - name: Build phpadmin
      run: docker build . --file Dockerfile.phpmyadmin -t usamashafique/php-app:phpadmin

    - name: List Docker Images
      run: docker images
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER_NAME}}
        password: ${{ secrets.USER_PASSWORD }}

    - name: Print Docker Image Details
      run: |
        docker images
        docker inspect usamashafique/php-app:latest
        while ! docker inspect usamashafique/php-app:latest &>/dev/null; do sleep 1; done

    - name: Push Docker image to Docker Hub
      run: docker push usamashafique/php-app:latest
    - name: Push Docker mysql  image to Docker Hub
      run: docker push usamashafique/php-app:db
    - name: Push Docker phpadmin  image to Docker Hub
      run: docker push usamashafique/php-app:phpadmin
