name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.16'

    - name: Install dependencies
      run: composer install

    - name: Verify PHPUnit installation
      run: ~/.composer/vendor/bin/phpunit --version

    - name: Add Composer bin directory to PATH
      run: echo "$HOME/.config/composer/vendor/bin" >> $GITHUB_PATH

    - name: Debug PHPUnit installation
      run: ls -la ~/.composer/vendor/bin

    - name: Lint PHP files
      run: php -l .

    - name: Run PHPUnit tests
      run: phpunit
